package com.leejordan.studygroupapp;

public class Subjects {
    static final String[] SUBJECTS = {"Biology",
            "Chemistry",
            "Physics",
            "Earth Science",
            "Pre-Algebra",
            "Algebra",
            "Statistics",
            "Pre-Calculus",
            "Trigonometry",
            "Calculus",
            "Multivariable Calculus",
            "World History",
            "US History",
            "European History",
            "English",
            "French",
            "Spanish",
            "German",
            "Latin",
            "Computer Science",
            "Physical Education",
            "Driver Education",
            "Health",
            "Art",
            "Art History",
            "Band",
            "Orchestra",
            "Chorus",
            "Music Theory",
            "Math",
            "Government",
            "Engineering",
            "Science",
            "Mobile App Development",
            "Web App Development",
            "Artificial Intelligence",
            "Philosophy",
            "Economics",
    };

    static final String[] CLASS_TYPES = {
            "Regular",
            "Honors",
            "AP",
            "IB",
            "Other"};
}
